---
version: "2"
plugins:
  duplication:
    enabled: true
    exclude_paths:
      - spec/
      - lib/seccomp-tools/asm/sasm.tab.rb
checks:
  file-lines:
    enabled: false
  method-count:
    enabled: false
  method-complexity:
    enabled: false
