#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.16
# from Racc grammar file "".
#

require 'racc/parser.rb'

require 'seccomp-tools/asm/scalar'
require 'seccomp-tools/asm/scanner'
require 'seccomp-tools/asm/statement'

module SeccompTools
  module Asm
    class SeccompAsmParser < Racc::Parser

module_eval(<<'...end sasm.y/module_eval...', 'sasm.y', 110)
  def initialize(scanner)
    @scanner = scanner
    super()
  end

  # @return [Array<Statement>]
  def parse
    @tokens = @scanner.scan.dup
    @cur_idx = 0
    do_parse
  end

  def next_token
    token = @tokens[@cur_idx]
    return [false, '$'] if token.nil?

    @cur_idx += 1
    [token.sym, token.str]
  end

  def on_error(t, val, vstack)
    raise_error("unexpected string #{last_token.str.inspect}")
  end

  # @param [String] msg
  # @param [Integer] offset
  # @private
  def raise_error(msg, offset = 0)
    raise SeccompTools::ParseError, @scanner.format_error(last_token(offset), msg)
  end

  # @param [Integer] off
  #   0 for the last parsed token, -n for the n-th previous parsed token, n for the future n-th token.
  def last_token(off = 0)
    @tokens[@cur_idx - 1 + off]
  end

...end sasm.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    24,    32,     6,    12,    32,    16,    42,    42,    19,    28,
    20,    37,    21,    37,     6,    12,    42,    16,    22,   114,
    19,    37,    20,    79,    21,    23,    34,    61,    23,    34,
    22,    22,     6,    12,    79,    16,    61,    23,    19,    61,
    20,    42,    21,    61,    44,    34,   103,    44,    22,    49,
    61,    53,    42,    61,    58,    23,    34,    54,    55,    56,
    59,    21,    53,    23,    28,    61,    37,    70,    54,    55,
    56,    19,    19,    44,    23,    21,    53,    74,    75,    76,
    77,    22,    54,    55,    56,    53,    61,    61,    23,    23,
    95,    54,    55,    56,    53,    58,   103,    23,   105,   106,
    54,    55,    56,    53,   103,   105,    23,   nil,    22,    54,
    55,    56,    53,    61,   nil,    23,   nil,   nil,    54,    55,
    56,    53,   nil,   nil,    23,   nil,   nil,    54,    55,    56,
    53,   nil,   nil,    23,   nil,    22,    54,    55,    56,    53,
    61,   nil,    23,   nil,    22,    54,    55,    56,   nil,    61,
   nil,    23 ]

racc_action_check = [
     1,    12,     1,     1,    73,     1,    16,    45,     1,     2,
     1,    13,     1,    14,     0,     0,    39,     0,     1,   109,
     0,    15,     0,    36,     0,     1,    12,    45,    16,    73,
     0,    39,    29,    29,   100,    29,   109,     0,    29,    36,
    29,    20,    29,   119,    17,    36,   119,    19,    29,    20,
   100,    20,    38,    29,    21,    29,   100,    20,    20,    20,
    24,    38,    38,    20,    25,    27,    31,    35,    38,    38,
    38,    88,   116,    43,    38,    35,    35,    35,    35,    35,
    35,    35,    35,    35,    35,    52,    88,   116,    35,    49,
    70,    52,    52,    52,    57,    76,    92,    52,    93,    96,
    57,    57,    57,    64,   101,   107,    57,   nil,    64,    64,
    64,    64,    91,    64,   nil,    64,   nil,   nil,    91,    91,
    91,    97,   nil,   nil,    91,   nil,   nil,    97,    97,    97,
    98,   nil,   nil,    97,   nil,    98,    98,    98,    98,   115,
    98,   nil,    98,   nil,   115,   115,   115,   115,   nil,   115,
   nil,   115 ]

racc_action_pointer = [
    12,     0,   -13,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    -3,   -13,   -11,    -3,     3,    35,   nil,    38,
    38,    27,   nil,   nil,    60,    42,   nil,    42,   nil,    30,
   nil,    42,   nil,   nil,   nil,    63,    16,   nil,    49,    13,
   nil,   nil,   nil,    64,   nil,     4,   nil,   nil,   nil,    64,
   nil,   nil,    72,   nil,   nil,   nil,   nil,    81,   nil,   nil,
   nil,   nil,   nil,   nil,    90,   nil,   nil,   nil,   nil,   nil,
    87,   nil,   nil,     0,   nil,   nil,    68,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    63,   nil,
   nil,    99,    70,    70,   nil,   nil,    86,   108,   117,   nil,
    27,    78,   nil,   nil,   nil,   nil,   nil,    77,   nil,    13,
   nil,   nil,   nil,   nil,   nil,   126,    64,   nil,   nil,    20,
   nil ]

racc_action_default = [
   -71,   -71,   -64,   -64,    -4,    -5,    -7,    -8,    -9,   -10,
   -11,   -12,   -55,   -64,   -71,   -71,   -71,   -71,   -64,   -71,
   -71,   -71,   -56,   -66,   -71,   -64,    -1,   -61,   -62,   -71,
   -64,   -71,   -49,   -50,   -70,   -71,   -71,   -65,   -71,   -71,
   -64,   -64,   -55,   -71,   -33,   -71,   -32,   -34,   -35,   -36,
   -38,   -51,   -71,   -57,   -58,   -59,   -60,   -71,   -68,   121,
    -2,   -63,    -3,    -6,   -71,   -48,   -14,   -20,   -21,   -22,
   -71,   -40,   -41,   -42,   -44,   -45,   -71,   -47,   -64,   -30,
   -31,   -15,   -17,   -18,   -19,   -16,   -53,   -54,   -71,   -25,
   -64,   -71,   -71,   -71,   -13,   -23,   -71,   -71,   -71,   -64,
   -71,   -71,   -52,   -67,   -39,   -69,   -43,   -71,   -29,   -27,
   -64,   -37,   -46,   -24,   -64,   -71,   -71,   -64,   -26,   -71,
   -28 ]

racc_goto_table = [
    29,    67,    50,    78,    80,    31,    57,    18,    18,    26,
    36,    14,    14,    99,   104,    45,   102,    35,    38,    39,
    82,    69,    41,    18,    83,   111,    48,    64,   112,    43,
    94,    46,    60,     1,    92,    65,    18,    88,    36,    93,
    14,   118,    62,   120,    84,    86,     2,    25,    63,    30,
    87,    90,    66,    81,    85,    89,    91,    68,    40,   113,
    47,    97,    73,   nil,   108,   nil,    96,   110,    80,   nil,
   nil,   nil,   nil,   101,   nil,    98,   nil,   nil,   nil,   107,
   nil,   117,   nil,   nil,   nil,   nil,   nil,   100,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   109,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   115,   nil,   nil,
   nil,   116,   nil,   nil,   119 ]

racc_goto_check = [
     5,    14,    22,    28,    30,    35,    32,    27,    27,     3,
     5,    18,    18,    11,    33,     5,    29,    16,    16,    16,
    22,    20,    15,    27,    20,    29,    15,     5,    33,    26,
    14,    26,     3,     1,    22,    16,    27,     5,     5,    22,
    18,    11,     6,    29,    15,    15,     2,     2,     7,    13,
    18,    15,    17,    19,    21,    26,    27,    23,    24,    25,
    31,    32,    34,   nil,    14,   nil,    35,    28,    30,   nil,
   nil,   nil,   nil,    22,   nil,     5,   nil,   nil,   nil,    22,
   nil,    14,   nil,   nil,   nil,   nil,   nil,     5,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     5,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5,   nil,   nil,
   nil,     5,   nil,   nil,     5 ]

racc_goto_pointer = [
   nil,    33,    46,     7,   nil,    -3,    13,    19,   nil,   nil,
   nil,   -75,   nil,    37,   -34,     6,     4,    17,    11,    15,
   -14,    15,   -18,    22,    42,   -50,    12,     7,   -33,   -76,
   -32,    40,   -15,   -79,    27,    -7,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     3,    27,     4,     5,     7,     8,
     9,    10,    11,   nil,   nil,    13,   nil,   nil,    71,   nil,
    15,   nil,    72,   nil,    17,   nil,   nil,    52,   nil,   nil,
    33,   nil,   nil,   nil,   nil,   nil,    51 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 31, :_reduce_1,
  3, 31, :_reduce_2,
  3, 32, :_reduce_3,
  1, 32, :_reduce_4,
  1, 34, :_reduce_5,
  3, 34, :_reduce_6,
  1, 37, :_reduce_7,
  1, 36, :_reduce_8,
  1, 36, :_reduce_9,
  1, 36, :_reduce_10,
  1, 36, :_reduce_11,
  1, 36, :_reduce_12,
  4, 38, :_reduce_13,
  3, 39, :_reduce_14,
  3, 39, :_reduce_15,
  3, 39, :_reduce_16,
  1, 49, :_reduce_none,
  1, 49, :_reduce_none,
  1, 49, :_reduce_none,
  1, 47, :_reduce_none,
  1, 47, :_reduce_21,
  1, 47, :_reduce_none,
  2, 47, :_reduce_23,
  6, 40, :_reduce_24,
  3, 40, :_reduce_25,
  3, 55, :_reduce_26,
  0, 55, :_reduce_27,
  9, 54, :_reduce_28,
  5, 54, :_reduce_29,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  2, 41, :_reduce_32,
  1, 56, :_reduce_33,
  2, 42, :_reduce_34,
  1, 61, :_reduce_none,
  1, 61, :_reduce_36,
  4, 61, :_reduce_37,
  1, 61, :_reduce_none,
  4, 50, :_reduce_39,
  1, 44, :_reduce_none,
  1, 44, :_reduce_41,
  1, 53, :_reduce_none,
  3, 53, :_reduce_43,
  1, 53, :_reduce_44,
  1, 53, :_reduce_45,
  4, 64, :_reduce_46,
  1, 64, :_reduce_47,
  2, 43, :_reduce_48,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 52, :_reduce_51,
  3, 52, :_reduce_52,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  1, 45, :_reduce_55,
  1, 48, :_reduce_56,
  1, 66, :_reduce_57,
  1, 66, :_reduce_58,
  1, 66, :_reduce_59,
  1, 66, :_reduce_60,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  2, 35, :_reduce_none,
  0, 35, :_reduce_none,
  1, 46, :_reduce_none,
  1, 57, :_reduce_none,
  1, 59, :_reduce_none,
  1, 62, :_reduce_none,
  1, 63, :_reduce_none,
  1, 60, :_reduce_none ]

racc_reduce_n = 71

racc_shift_n = 121

racc_token_table = {
  false => 0,
  :error => 1,
  :SYMBOL => 2,
  :A => 3,
  :ALU_OP => 4,
  :IF => 5,
  :ELSE => 6,
  :COMPARE => 7,
  :GOTO => 8,
  :GOTO_SYMBOL => 9,
  :RETURN => 10,
  :ACTION => 11,
  :MEM => 12,
  :INT => 13,
  :SYS_NUMBER => 14,
  :ARCH => 15,
  :ARGS => 16,
  :INSTRUCTION_POINTER => 17,
  :X => 18,
  :HEX_INT => 19,
  :ARCH_VAL => 20,
  :SYSCALL => 21,
  :false => 22,
  :NEWLINE => 23,
  "=" => 24,
  "(" => 25,
  ")" => 26,
  "[" => 27,
  "]" => 28,
  "&" => 29 }

racc_nt_base = 30

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SYMBOL",
  "A",
  "ALU_OP",
  "IF",
  "ELSE",
  "COMPARE",
  "GOTO",
  "GOTO_SYMBOL",
  "RETURN",
  "ACTION",
  "MEM",
  "INT",
  "SYS_NUMBER",
  "ARCH",
  "ARGS",
  "INSTRUCTION_POINTER",
  "X",
  "HEX_INT",
  "ARCH_VAL",
  "SYSCALL",
  "false",
  "NEWLINE",
  "\"=\"",
  "\"(\"",
  "\")\"",
  "\"[\"",
  "\"]\"",
  "\"&\"",
  "$start",
  "prog",
  "normalized_statement",
  "terminator",
  "symbols",
  "newlines",
  "statement",
  "symbol",
  "arithmetic",
  "assignment",
  "conditional",
  "goto_expr",
  "return_stat",
  "alu_op_eq",
  "x_constexpr",
  "a",
  "ASSIGN",
  "a_rval",
  "x",
  "x_rval",
  "memory",
  "ax",
  "constexpr",
  "argument",
  "comparison",
  "else_block",
  "goto_symbol",
  "LPAREN",
  "compare",
  "RPAREN",
  "AND",
  "ret_val",
  "LBRACK",
  "RBRACK",
  "argument_long",
  "alu_op",
  "number" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'sasm.y', 3)
  def _reduce_1(val, _values)
     [val[0]]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 4)
  def _reduce_2(val, _values)
     val[0] << val[1]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 5)
  def _reduce_3(val, _values)
     Statement.new(*val[2], val[0])
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 6)
  def _reduce_4(val, _values)
     Statement.new(*val[0], [])
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 7)
  def _reduce_5(val, _values)
     val
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 8)
  def _reduce_6(val, _values)
     val[0] << val[2]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 10)
  def _reduce_7(val, _values)
                t = val[0]
            raise_error("'next' is a reserved label") if t == 'next'
            last_token

  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 14)
  def _reduce_8(val, _values)
     [:alu, val[0]]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 15)
  def _reduce_9(val, _values)
     [:assign, val[0]]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 16)
  def _reduce_10(val, _values)
     [:if, val[0]]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 17)
  def _reduce_11(val, _values)
     [:if, [nil, val[0], val[0]]]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 18)
  def _reduce_12(val, _values)
     [:ret, val[0]]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 19)
  def _reduce_13(val, _values)
     [val[1], val[3]]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 20)
  def _reduce_14(val, _values)
     [val[0], val[2]]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 21)
  def _reduce_15(val, _values)
     [val[0], val[2]]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 22)
  def _reduce_16(val, _values)
     [val[0], val[2]]
  end
.,.,

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

module_eval(<<'.,.,', 'sasm.y', 29)
  def _reduce_21(val, _values)
     Scalar::Data.new(val[0])
  end
.,.,

# reduce 22 omitted

module_eval(<<'.,.,', 'sasm.y', 33)
  def _reduce_23(val, _values)
              raise_error('do you mean A = -A?', -1) if val[0] != '-'
          :neg

  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 36)
  def _reduce_24(val, _values)
     [val[1], val[3], val[5]]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 37)
  def _reduce_25(val, _values)
     val
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 38)
  def _reduce_26(val, _values)
     val[2]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 39)
  def _reduce_27(val, _values)
     :next
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 40)
  def _reduce_28(val, _values)
     [val[4], val[6]]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 41)
  def _reduce_29(val, _values)
     [val[2], val[4]]
  end
.,.,

# reduce 30 omitted

# reduce 31 omitted

module_eval(<<'.,.,', 'sasm.y', 44)
  def _reduce_32(val, _values)
     val[1]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 45)
  def _reduce_33(val, _values)
     last_token
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 46)
  def _reduce_34(val, _values)
     val[1]
  end
.,.,

# reduce 35 omitted

module_eval(<<'.,.,', 'sasm.y', 48)
  def _reduce_36(val, _values)
     Const::BPF::ACTION[val[0].to_sym]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 50)
  def _reduce_37(val, _values)
                 Const::BPF::ACTION[val[0].to_sym] |
               (val[2] & Const::BPF::SECCOMP_RET_DATA)

  end
.,.,

# reduce 38 omitted

module_eval(<<'.,.,', 'sasm.y', 55)
  def _reduce_39(val, _values)
                idx = val[2]
            raise_error(format("Index of mem[] must between 0 and 15, got %d", idx), -1) unless idx.between?(0, 15)
            Scalar::Mem.new(idx)

  end
.,.,

# reduce 40 omitted

module_eval(<<'.,.,', 'sasm.y', 60)
  def _reduce_41(val, _values)
     Scalar::ConstVal.new(val[0])
  end
.,.,

# reduce 42 omitted

module_eval(<<'.,.,', 'sasm.y', 63)
  def _reduce_43(val, _values)
                  if val[1] != '>>' || val[2].to_i != 4
                off = val[1] == '>>' ? 0 : -1
                raise_error("operator after an argument can only be '>> 4'", off)
              end
              val[0] + 4

  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 69)
  def _reduce_44(val, _values)
     0
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 70)
  def _reduce_45(val, _values)
     4
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 73)
  def _reduce_46(val, _values)
                       idx = val[2]
                   raise_error(format('Index of args[] must between 0 and 5, got %d', idx), -1) unless idx.between?(0, 5)
                   16 + idx * 8

  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 77)
  def _reduce_47(val, _values)
     8
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 78)
  def _reduce_48(val, _values)
     val[0] + val[1]
  end
.,.,

# reduce 49 omitted

# reduce 50 omitted

module_eval(<<'.,.,', 'sasm.y', 81)
  def _reduce_51(val, _values)
     val[0] & 0xffffffff
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 82)
  def _reduce_52(val, _values)
     val[1]
  end
.,.,

# reduce 53 omitted

# reduce 54 omitted

module_eval(<<'.,.,', 'sasm.y', 85)
  def _reduce_55(val, _values)
     Scalar::A.instance
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 86)
  def _reduce_56(val, _values)
     Scalar::X.instance
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 87)
  def _reduce_57(val, _values)
     val[0].to_i
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 88)
  def _reduce_58(val, _values)
     val[0].to_i(16)
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 89)
  def _reduce_59(val, _values)
     Const::Audit::ARCH[val[0]]
  end
.,.,

module_eval(<<'.,.,', 'sasm.y', 90)
  def _reduce_60(val, _values)
     @scanner.syscalls[val[0].to_sym]
  end
.,.,

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

def _reduce_none(val, _values)
  val[0]
end

    end   # class SeccompAsmParser
  end   # module Asm
end   # module SeccompTools


