name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  test:

    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.ruby-version == 'head' }}
    strategy:
      matrix:
        os: [ubuntu]
        ruby-version: ['3.3', '3.4', '4.0', 'head']

    steps:
    - uses: actions/checkout@v2
    - name: Strip lockfile on Ruby Head to bypass mismatch bundler version
      if: matrix.ruby-version == 'head'
      run: |
        echo "Removing Gemfile.lock"
        rm -f Gemfile.lock
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install packages
      run: sudo apt update && sudo apt install -yy gcc
    - name: Bundle install
      run: |
        sudo env "PATH=$PATH" bundle config set path 'vendor/bundle'
        sudo env "PATH=$PATH" bundle install --jobs=3 --retry=3
    - name: Run tests
      run: sudo env "PATH=$PATH" CI=1 bundle exec rake
    - name: Publish code coverage
      if: ${{ success() }}
      uses: qltysh/qlty-action/coverage@v1
      with:
        oidc: true
        files: coverage/coverage.json
